server:
  port: 8080
  compression:
    enabled: true
  servlet:
    contextPath: /
    session:
      cookie:
        name: gerenciador-gastos
  max-http-header-size: 2MB
  tomcat:
    max-http-post-size: 15MB

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: gerenciador-gastos
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_EMPTY
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:runtime;DB_CLOSE_DELAY=-1
  data:
    jpa:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.security: ERROR
    org.hibernate: INFO
